; PlatformIO Project Configuration File

[platformio]
src_dir = .

[env:esp32c3]
platform = espressif32@6.5.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags =
    -DESP32_C3
    -DHAS_BT
    -DCORE_DEBUG_LEVEL=0
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

board_build.partitions = min_spiffs.csv
upload_speed = 921600

lib_deps =
    mathertel/OneButton @ ^2.5.0
    bblanchon/ArduinoJson @ ^6.21.3
    h2zero/NimBLE-Arduino @ ^1.4.0
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
